### ISSUE TITLE
[Feature] Enhancing Money Update Event

### ISSUE THREAD

**Issue by Thunder33345** [ParoxityTeam/ParoxityEcon#6] opened 2020-06-09 21:21 UTC
There should be a way to get "post" and "pre" changes

There should also be a CLAUSE field of sorts, or ideally just extend it  ex MoneyReduceEvent extend MoneyUpdateEvent
so plugins can at the very least understand the events origins, even if they cant cancel it

**Comment by SOF3** [comment] 2020-06-10 07:22
Extending events directly has proven to be an antipattern. Consider creating a `TransactionCause` interface that initiators of money updates can implement.

**Comment by Ifera** [comment] 2021-03-19 19:30
`TransactionCause`? 
Umm what should this be? Like who initiated the change? 
Also what should this be? Any example causes? 

Shouldn't PRE and POST be okay?

**Comment by SOF3** [comment] 2021-03-20 03:20
why need `pre` and `post`? aren't event priorities enough for that?

**Comment by Ifera** [comment] 2021-03-20 07:33
I am not sure if we are on the same page here. What I meant by `pre` and `post` was of adding `oldMoney` and `newMoney` params to the MoneyUpdateEvent.

**Comment by SOF3** [comment] 2021-03-20 08:09
Oh, fine then.

Anyway it would be useful for plugins to provide their full stack of information regarding the cause of transaction, e.g. who initiated it, any other objects (e.g. shops) involved, etc.

**Comment by Ifera** [comment] 2021-03-21 15:02
On second thought, I don't think that having the old money and the new money is really necessary.. Like what would be the use case for this? The event cannot be cancelled so what purpose will the old money serve here? 
Further, ParoxityEcon is not aware of the players current balance when adding, deducting or setting it, at all. This is done via the SQL query in order to keep the transactions atomic. 
Closing the issue unless someone could convince me as to why this would be needed.

**Closed as completed by Ifera** 2021-03-21 15:02 UTC
Labels: Resolution: Declined

**Comment by Thunder33345** [comment] 2021-03-23 18:45
> ParoxityEcon is not aware of the players current balance when adding, deducting or setting it, at all. 

what about including balance change, it needs to be aware of how much to deduct or add to the very least

**Comment by Ifera** [comment] 2021-03-24 00:05
> it needs to be aware of how much to deduct or add to the very least

That its aware off. Also there is cache, but its not recommended to be used other than for display stuff etc. 
Its just that to keep the transactions atomic, the pligin only supplies that amount to add/deduct to the query, the rest is handled within the query. And so it doesn't keep track of what the players balance was before the transaction.

**Comment by SOF3** [comment] 2021-03-24 00:54
> > it needs to be aware of how much to deduct or add to the very least
> 
> That its aware off. Also there is cache, but its not recommended to be used other than for display stuff etc.
> Its just that to keep the transactions atomic, the pligin only supplies that amount to add/deduct to the query, the rest is handled within the query. And so it doesn't keep track of what the players balance was before the transaction.

That's what thunder is saying.

Three types of operations:

- direct update
- add a value to balance
- multiply a value to balance

Expose this information in the event.

**Comment by Ifera** [comment] 2021-03-24 05:18
If that is really needed then please feel free to PR. 🙂
